version: '3.8'

services:
  web:
    image: my-docker-image:latest
    ports:
      - "80:80"
    environment:
      - ENV_VAR=example

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
